### ISSUE TITLE
/parties endpoint responding with code error

### ISSUE THREAD

**Issue by tarmo-profi** [FIWARE/ishare-satellite#13]
Hello,

When requesting /parties endpoint with some parameters 
`/parties?eori=EU.EORI.FICAVEROCK&certificate_subject_name=C%3DFI%2C+ST%3DTampere%2C+L%3DTampere%2C+O%3DLuolakallio+Client%2C+CN%3DLuolakallio-Client%2C+E%3Dclient%40luolakallio.fi%2C+serialNumber%3DEU.EORI.FICAVEROCK&active_only=true`

Satellite then responds with this:
`{"code":500,"message":"Internal server error: local variable 'ex' referenced before assignment"}`

---

It seems to be a logic error in python: https://github.com/FIWARE/ishare-satellite/blob/main/api/parties.py#L95

**Comment by dwendland** [comment]
Thanks for pointing this out. This should have been fixed with https://github.com/FIWARE/ishare-satellite/pull/14.
