### ISSUE TITLE
Token endpoint path does not conform to iSHARE documentation

### ISSUE THREAD

**Issue by remvee** [FIWARE/ishare-satellite#18]
Currently the token endpoint is at `/token` but iSHARE describes it as being at `/connect/token`.  See also:

  https://app.swaggerhub.com/apis/iSHARE/i-share_satellite/0.2#/Satellite/%2Fconnect%2Ftoken

and:

  https://dev.ishareworks.org/common/token.html#example

**Comment by wistefan** [comment]
Apparently, the iShare-documentation/spec is rather vague on that aspect. On swaggerhub(which defines v0.2, a version that does that is different to the "latest" 1.11 release of the spec) its defined as /connect/token, on dev.ishareworks the path is not defined at all, just mentioned in an example and in the spec at atlassian(https://ishareworks.atlassian.net/) it refers to the  /oauth2.0/token  path from the OAuth-2 standard. Therefor we decided to just go with /token.
If you require a different prefix, we would welcome a PR making this configurable. 
Best,
Stefan

**Comment by remvee** [comment]
According to the people at iSHARE, `/connect/token` is the correct path and pointed me to https://so.ishare.eu/connect/token (not sure how that's authorative but that's what I got) but I agree the documentation is sloppy.

I'm not sure what a PR would look like because according to the swaggerhub stuff and dev.ishareworks.org, the token endpoint seems to be an outlier; it's the only endpoint with a multi part path so a prefix would only apply to token.  Or the PR should make all paths configurable which seems like overkill to me.

Another option is to allow both `/token` and `/connect/token`, WDYT?

**Comment by wistefan** [comment]
I would also be fine with that.

**Comment by remvee** [comment]
See: #20
